-- =============================================
-- V1: Initial Schema
-- AI Restaurant Phone Ordering Platform
-- =============================================
-- Notes:
--   1. Primary keys use Snowflake ID (generated by application)
--   2. No foreign key constraints (handled at application level)
--   3. Indexes kept for query performance

-- =============================================
-- 1. Restaurant
-- =============================================
CREATE TABLE restaurant (
    id            BIGINT       PRIMARY KEY,
    name          VARCHAR(200) NOT NULL,
    description   TEXT,
    address       VARCHAR(500) NOT NULL,
    phone         VARCHAR(50)  NOT NULL,
    timezone      VARCHAR(50)  NOT NULL DEFAULT 'America/New_York',
    logo          VARCHAR(500),
    images        TEXT[],
    status        VARCHAR(20)  NOT NULL DEFAULT 'OPEN',  -- OPEN / PAUSED / CLOSED
    created_at    TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at    TIMESTAMP    NOT NULL DEFAULT now()
);

-- =============================================
-- 2. Operating Hours
-- =============================================
CREATE TABLE operating_hours (
    id              BIGINT       PRIMARY KEY,
    restaurant_id   BIGINT       NOT NULL,
    day_of_week     VARCHAR(10)  NOT NULL,  -- MON/TUE/WED/THU/FRI/SAT/SUN
    order_type      VARCHAR(20),            -- DINE_IN / TAKEOUT / null(=all)
    open_time       TIME         NOT NULL,
    close_time      TIME         NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE INDEX idx_operating_hours_restaurant ON operating_hours(restaurant_id);

CREATE TABLE special_date_hours (
    id              BIGINT       PRIMARY KEY,
    restaurant_id   BIGINT       NOT NULL,
    date            DATE         NOT NULL,
    is_closed       BOOLEAN      NOT NULL DEFAULT FALSE,
    open_time       TIME,
    close_time      TIME,
    note            VARCHAR(200),
    created_at      TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE INDEX idx_special_date_hours_restaurant ON special_date_hours(restaurant_id);

-- =============================================
-- 3. Menu - Category
-- =============================================
CREATE TABLE menu_category (
    id              BIGINT       PRIMARY KEY,
    restaurant_id   BIGINT       NOT NULL,
    name            VARCHAR(100) NOT NULL,
    description     TEXT,
    sort_order      INT          NOT NULL DEFAULT 0,
    created_at      TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE INDEX idx_menu_category_restaurant ON menu_category(restaurant_id);

-- =============================================
-- 4. Menu - Item
-- =============================================
CREATE TABLE menu_item (
    id                    BIGINT         PRIMARY KEY,
    restaurant_id         BIGINT         NOT NULL,
    category_id           BIGINT         NOT NULL,
    name                  VARCHAR(200)   NOT NULL,
    description           TEXT,
    price                 DECIMAL(10,2)  NOT NULL DEFAULT 0,
    image                 VARCHAR(500),
    allergens             TEXT[],
    tags                  TEXT[],
    available             BOOLEAN        NOT NULL DEFAULT TRUE,
    sort_order            INT            NOT NULL DEFAULT 0,
    -- inline availability schedule
    available_days        TEXT[],         -- e.g. {MON,TUE,WED} or null = every day
    available_start_time  TIME,           -- null = from opening
    available_end_time    TIME,           -- null = until closing
    created_at            TIMESTAMP      NOT NULL DEFAULT now(),
    updated_at            TIMESTAMP      NOT NULL DEFAULT now()
);

CREATE INDEX idx_menu_item_restaurant ON menu_item(restaurant_id);
CREATE INDEX idx_menu_item_category ON menu_item(category_id);

-- =============================================
-- 5. Menu - Item Variant
-- =============================================
CREATE TABLE menu_item_variant (
    id          BIGINT         PRIMARY KEY,
    item_id     BIGINT         NOT NULL,
    name        VARCHAR(100)   NOT NULL,
    price       DECIMAL(10,2)  NOT NULL,
    sort_order  INT            NOT NULL DEFAULT 0,
    created_at  TIMESTAMP      NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP      NOT NULL DEFAULT now()
);

CREATE INDEX idx_menu_item_variant_item ON menu_item_variant(item_id);

-- =============================================
-- 5.1 Menu - Item Alias (for AI recognition)
-- =============================================
CREATE TABLE menu_item_alias (
    id          BIGINT       PRIMARY KEY,
    item_id     BIGINT       NOT NULL,
    alias_name  VARCHAR(200) NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE INDEX idx_menu_item_alias_item ON menu_item_alias(item_id);

-- =============================================
-- 6. Menu - Modifier Group
-- =============================================
CREATE TABLE modifier_group (
    id              BIGINT       PRIMARY KEY,
    item_id         BIGINT       NOT NULL,
    name            VARCHAR(100) NOT NULL,
    selection_type  VARCHAR(10)  NOT NULL DEFAULT 'SINGLE',  -- SINGLE / MULTI
    required        BOOLEAN      NOT NULL DEFAULT FALSE,
    max_selections  INT          NOT NULL DEFAULT 0,          -- 0 = unlimited (for MULTI)
    sort_order      INT          NOT NULL DEFAULT 0,
    created_at      TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE INDEX idx_modifier_group_item ON modifier_group(item_id);

-- =============================================
-- 7. Menu - Modifier Option
-- =============================================
CREATE TABLE modifier_option (
    id              BIGINT         PRIMARY KEY,
    group_id        BIGINT         NOT NULL,
    name            VARCHAR(100)   NOT NULL,
    extra_price     DECIMAL(10,2)  NOT NULL DEFAULT 0,
    is_default      BOOLEAN        NOT NULL DEFAULT FALSE,
    sort_order      INT            NOT NULL DEFAULT 0,
    created_at      TIMESTAMP      NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP      NOT NULL DEFAULT now()
);

CREATE INDEX idx_modifier_option_group ON modifier_option(group_id);

-- =============================================
-- 8. Combo
-- =============================================
CREATE TABLE combo (
    id                    BIGINT         PRIMARY KEY,
    restaurant_id         BIGINT         NOT NULL,
    name                  VARCHAR(200)   NOT NULL,
    description           TEXT,
    price                 DECIMAL(10,2)  NOT NULL,
    image                 VARCHAR(500),
    available             BOOLEAN        NOT NULL DEFAULT TRUE,
    -- inline availability schedule
    available_days        TEXT[],
    available_start_time  TIME,
    available_end_time    TIME,
    created_at            TIMESTAMP      NOT NULL DEFAULT now(),
    updated_at            TIMESTAMP      NOT NULL DEFAULT now()
);

CREATE INDEX idx_combo_restaurant ON combo(restaurant_id);

-- =============================================
-- 9. Combo Group
-- =============================================
CREATE TABLE combo_group (
    id          BIGINT       PRIMARY KEY,
    combo_id    BIGINT       NOT NULL,
    name        VARCHAR(100) NOT NULL,
    pick_count  INT          NOT NULL DEFAULT 1,
    required    BOOLEAN      NOT NULL DEFAULT TRUE,
    sort_order  INT          NOT NULL DEFAULT 0,
    created_at  TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE INDEX idx_combo_group_combo ON combo_group(combo_id);

-- =============================================
-- 10. Combo Group Item (join table)
-- =============================================
CREATE TABLE combo_group_item (
    id          BIGINT     PRIMARY KEY,
    group_id    BIGINT     NOT NULL,
    item_id     BIGINT     NOT NULL,
    created_at  TIMESTAMP  NOT NULL DEFAULT now()
);

CREATE INDEX idx_combo_group_item_group ON combo_group_item(group_id);
CREATE UNIQUE INDEX uk_combo_group_item ON combo_group_item(group_id, item_id);

-- =============================================
-- 11. Dining Section
-- =============================================
CREATE TABLE dining_section (
    id              BIGINT         PRIMARY KEY,
    restaurant_id   BIGINT         NOT NULL,
    name            VARCHAR(100)   NOT NULL,
    smoking         BOOLEAN        NOT NULL DEFAULT FALSE,
    surcharge       DECIMAL(10,2),
    note            TEXT,
    created_at      TIMESTAMP      NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP      NOT NULL DEFAULT now()
);

CREATE INDEX idx_dining_section_restaurant ON dining_section(restaurant_id);

-- =============================================
-- 12. Dining Table
-- =============================================
CREATE TABLE dining_table (
    id              BIGINT       PRIMARY KEY,
    restaurant_id   BIGINT       NOT NULL,
    section_id      BIGINT       NOT NULL,
    table_number    VARCHAR(50)  NOT NULL,
    capacity        INT          NOT NULL,
    mergeable       BOOLEAN      NOT NULL DEFAULT FALSE,
    status          VARCHAR(20)  NOT NULL DEFAULT 'AVAILABLE',  -- AVAILABLE / MAINTENANCE
    created_at      TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE INDEX idx_dining_table_restaurant ON dining_table(restaurant_id);
CREATE INDEX idx_dining_table_section ON dining_table(section_id);

-- =============================================
-- 13. Restaurant Settings
-- (1:1 with restaurant, all config in one table)
-- =============================================
CREATE TABLE restaurant_settings (
    id                          BIGINT         PRIMARY KEY,
    restaurant_id               BIGINT         NOT NULL UNIQUE,

    -- order types
    accepted_order_types        TEXT[]         NOT NULL DEFAULT '{DINE_IN,TAKEOUT}',

    -- last order
    last_order_minutes_before_close INT        NOT NULL DEFAULT 30,

    -- tax
    tax_rate                    DECIMAL(5,3)   NOT NULL DEFAULT 0,
    tax_name                    VARCHAR(50)    NOT NULL DEFAULT 'Sales Tax',
    tax_inclusive               BOOLEAN        NOT NULL DEFAULT FALSE,

    -- dine-in
    reservation_enabled         BOOLEAN        NOT NULL DEFAULT TRUE,
    max_advance_days            INT            NOT NULL DEFAULT 30,
    min_advance_minutes         INT            NOT NULL DEFAULT 60,
    max_reservations_per_slot   INT            NOT NULL DEFAULT 10,
    section_preference_enabled  BOOLEAN        NOT NULL DEFAULT TRUE,
    pre_order_enabled           BOOLEAN        NOT NULL DEFAULT FALSE,
    pre_order_required          BOOLEAN        NOT NULL DEFAULT FALSE,

    -- takeout
    min_prep_minutes            INT            NOT NULL DEFAULT 20,
    scheduled_pickup_enabled    BOOLEAN        NOT NULL DEFAULT TRUE,
    max_scheduled_advance_hours INT            NOT NULL DEFAULT 24,
    max_orders_per_slot         INT            NOT NULL DEFAULT 20,
    pickup_instructions         TEXT,

    -- cancellation
    allow_cancellation          BOOLEAN        NOT NULL DEFAULT TRUE,
    cancel_deadline_hours       INT            NOT NULL DEFAULT 0,
    cancel_reason_required      BOOLEAN        NOT NULL DEFAULT FALSE,
    cancel_policy_note          TEXT,

    -- queue
    queue_enabled               BOOLEAN        NOT NULL DEFAULT FALSE,
    estimated_wait_strategy     VARCHAR(200),

    -- capacity
    peak_hour_order_limit       INT,

    -- auto confirm
    auto_confirm_enabled        BOOLEAN        NOT NULL DEFAULT TRUE,  -- if false, orders need manual confirmation

    -- parking
    has_parking                 BOOLEAN        NOT NULL DEFAULT FALSE,
    parking_type                VARCHAR(20),    -- OWN / PARTNER / STREET
    parking_capacity            INT,
    parking_fee_type            VARCHAR(30),    -- FREE / FREE_WITH_MIN_SPEND / HOURLY
    parking_free_with_min_spend DECIMAL(10,2),
    parking_hourly_rate         DECIMAL(10,2),
    parking_address             VARCHAR(500),
    parking_notes               TEXT,

    created_at                  TIMESTAMP      NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMP      NOT NULL DEFAULT now()
);

-- =============================================
-- 14. AI Phone Settings
-- =============================================
CREATE TABLE ai_phone_settings (
    id                  BIGINT       PRIMARY KEY,
    restaurant_id       BIGINT       NOT NULL UNIQUE,
    language            VARCHAR(10)  NOT NULL DEFAULT 'en',
    greeting_message    TEXT,
    escalation_phone    VARCHAR(50),
    escalation_triggers TEXT[]       DEFAULT '{CUSTOMER_REQUEST,AI_UNABLE,COMPLAINT}',
    created_at          TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at          TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE TABLE ai_phone_active_hours (
    id              BIGINT       PRIMARY KEY,
    settings_id     BIGINT       NOT NULL,
    day_of_week     VARCHAR(10)  NOT NULL,
    start_time      TIME         NOT NULL,
    end_time        TIME         NOT NULL,
    created_at      TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE INDEX idx_ai_phone_active_hours_settings ON ai_phone_active_hours(settings_id);

CREATE TABLE ai_phone_faq (
    id              BIGINT       PRIMARY KEY,
    settings_id     BIGINT       NOT NULL,
    question        TEXT         NOT NULL,
    answer          TEXT         NOT NULL,
    sort_order      INT          NOT NULL DEFAULT 0,
    created_at      TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE INDEX idx_ai_phone_faq_settings ON ai_phone_faq(settings_id);

CREATE TABLE ai_phone_instruction (
    id              BIGINT       PRIMARY KEY,
    settings_id     BIGINT       NOT NULL,
    instruction     TEXT         NOT NULL,
    sort_order      INT          NOT NULL DEFAULT 0,
    created_at      TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE INDEX idx_ai_phone_instruction_settings ON ai_phone_instruction(settings_id);

-- =============================================
-- 15. Orders
-- =============================================
CREATE TABLE orders (
    id                   BIGINT         PRIMARY KEY,
    restaurant_id        BIGINT         NOT NULL,
    order_number         VARCHAR(50)    NOT NULL UNIQUE,
    type                 VARCHAR(20)    NOT NULL,  -- DINE_IN / TAKEOUT
    status               VARCHAR(20)    NOT NULL DEFAULT 'PENDING',  -- PENDING / CONFIRMED / COMPLETED / CANCELLED

    -- customer
    customer_name        VARCHAR(100)   NOT NULL,
    customer_phone       VARCHAR(50)    NOT NULL,
    customer_notes       TEXT,

    -- dine-in fields
    reservation_date     DATE,
    reservation_time     TIME,
    party_size           INT,
    section_preference   VARCHAR(100),

    -- takeout fields
    pickup_time          TIMESTAMP,

    -- totals
    subtotal             DECIMAL(10,2)  NOT NULL DEFAULT 0,
    tax                  DECIMAL(10,2)  NOT NULL DEFAULT 0,
    total                DECIMAL(10,2)  NOT NULL DEFAULT 0,

    -- meta
    call_id              VARCHAR(200),
    cancel_reason        TEXT,
    confirmed_at         TIMESTAMP,          -- when the order was confirmed
    created_at           TIMESTAMP      NOT NULL DEFAULT now(),
    updated_at           TIMESTAMP      NOT NULL DEFAULT now()
);

CREATE INDEX idx_orders_restaurant ON orders(restaurant_id);
CREATE INDEX idx_orders_status ON orders(restaurant_id, status);
CREATE INDEX idx_orders_customer_phone ON orders(customer_phone);

-- =============================================
-- 16. Order Items
-- =============================================
CREATE TABLE order_item (
    id                  BIGINT         PRIMARY KEY,
    order_id            BIGINT         NOT NULL,
    item_id             BIGINT,
    combo_id            BIGINT,
    quantity            INT            NOT NULL DEFAULT 1,
    variant_name        VARCHAR(100),
    selected_modifiers  JSONB,          -- [{name, extra_price}]
    item_note           TEXT,
    subtotal            DECIMAL(10,2)  NOT NULL DEFAULT 0,
    created_at          TIMESTAMP      NOT NULL DEFAULT now(),
    updated_at          TIMESTAMP      NOT NULL DEFAULT now()
);

CREATE INDEX idx_order_item_order ON order_item(order_id);

-- =============================================
-- 17. Order Status Log (audit trail)
-- =============================================
CREATE TABLE order_status_log (
    id          BIGINT       PRIMARY KEY,
    order_id    BIGINT       NOT NULL,
    from_status VARCHAR(20),
    to_status   VARCHAR(20)  NOT NULL,
    reason      TEXT,
    created_at  TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE INDEX idx_order_status_log_order ON order_status_log(order_id);

-- =============================================
-- 18. Account
-- =============================================
CREATE TABLE account (
    id              BIGINT       PRIMARY KEY,
    restaurant_id   BIGINT       NOT NULL,
    email           VARCHAR(100) NOT NULL UNIQUE,
    password_hash   VARCHAR(200) NOT NULL,
    name            VARCHAR(100),
    role            VARCHAR(20)  NOT NULL DEFAULT 'ADMIN',  -- SUPER_ADMIN / ADMIN
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    last_login_at   TIMESTAMP,
    created_at      TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE INDEX idx_account_restaurant ON account(restaurant_id);
CREATE INDEX idx_account_email ON account(email);
